name: "H1-small-1m"
use_meta_learning: True  # H1: Meta-RL (uses prev_action/prev_reward)
env_id: "XLand-MiniGrid-R9-16x16"
benchmark_id: "small-1m"
total_timesteps: 1_000_000_000
num_envs: 8192
num_steps_per_env: 12800
num_steps_per_update: 256
update_epochs: 1
num_minibatches: 16
eval_num_envs: 2048
eval_num_episodes: 5
train_seed: 42
