env_id: "XLand-MiniGrid-R9-16x16"
benchmark_id: "trivial-1m"
total_timesteps: 10_000_000
num_envs: 512
num_steps_per_env: 12800
num_steps_per_update: 256
update_epochs: 1
num_minibatches: 16
eval_num_envs: 512
eval_num_episodes: 25
train_seed: 42
