project: "xminigrid-medium-1m"
name: "H1-medium-1m"
use_meta_learning: True
env_id: "XLand-MiniGrid-R9-16x16"
benchmark_id: "medium-1m"
total_timesteps: 5_000_000_000
num_envs: 16384
num_steps_per_env: 12800
num_steps_per_update: 256
update_epochs: 1
num_minibatches: 32
eval_num_envs: 4096
eval_num_episodes: 20
obs_emb_dim: 32
action_emb_dim: 32
